### ISSUE TITLE
Edit "Register" text on index page

### ISSUE THREAD

**Issue by baekusboo** [QAZIMAAZARSHAD/Movie-Streaming-Website#555]
Currently, I can access the website directly and access the links to watch the movies easily without logging in or registering myself. When I click the logo, I can view the movies and watch them easily. This defeats the whole purpose of having a login/ register feature on the website. I would suggest adding proper validation and verification in the login and sign-up forms (in the front end itself). 

Also, there is no login button and only a register button is present at first. When I click on the register button - It shows a normal login form instead of the signup form; The buttons are linked oppositely. The sign-in page is visible when clicking register. That can be updated.

![screenshot_1](https://user-images.githubusercontent.com/83155556/196615558-66a84e1b-e4e7-438f-aa2d-1184c16804ad.PNG)

Apart from these issues, the website design and interface are amazing! Good work Team! ^^

**Comment by QAZIMAAZARSHAD** [comment]
@baekusboo the hyperlink to the home page via logo image is created to bypass the login page for developers(to save time).

And on clicking register the user is redirected to the login page is correct because most of the times the user will be a returning user and he will login instead of sign up.
Sign up is only for first time users, so it should not be the first page.

**Comment by QAZIMAAZARSHAD** [comment]
I agree that register button on the index page redirecting to login page is odd.

So, edit the register text. Make it "Enter", or "Watch", or "Let's Go", or something unique and relevant(your choice).

**Comment by baekusboo** [comment]
Sure, thanks for assigning! I'll update the register text 👍🏽
