### ISSUE TITLE
Login/Sign-Up Page UI Update

### ISSUE THREAD

**Issue by AKC068** [QAZIMAAZARSHAD/Movie-Streaming-Website#67]
- [ ] I would like to work on this page as this is also an important part for a dynamic website so it should be attractive.
- [ ] I've some great UI ideas to implement on this site.
- [ ] `Suggestion` - Login and Sign-Up should be in one page only in different tabs. (UI idea)

@QAZIMAAZARSHAD can you please assign this issue to me as participant of LGM-SOC'21

**Comment by QAZIMAAZARSHAD** [comment]
> * [ ]  I would like to work on this page as this is also an important part for a dynamic website so it should be attractive.
> * [ ]  I've some great UI ideas to implement on this site.
> * [ ]  `Suggestion` - Login and Sign-Up should be in one page only in different tabs. (UI idea)
> 
> @QAZIMAAZARSHAD can you please assign this issue to me as participant of LGM-SOC'21

@AKC068 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/13.

Also, that issue has been resolved and will be closed soon.
And if you believe your design is better than the new one then you are welcome to open a new issue to improve it.
Wait till I merge the other PR. Then you can open another issue.

**Comment by AKC068** [comment]
Sure
